services:
  model:
    container_name: model
    build: ./containers/nn/
    environment:
      - DATABASE_URL=mongodb://database:27017/
    volumes:
      - ./containers/nn:/model
      - ./logs:/logs
    depends_on:
      - database
    restart: on-failure:3 

  database:
    ports:
      - 27017:27017
    image: "mongodb/mongodb-community-server"
