services:
  model:
    container_name: model
    build: ./containers/nn/
    environment:
      - DATABASE_URL=mongodb://database:27017/
    volumes:
      - ./containers/nn:/model
      - ./logs:/logs
    depends_on:
      meta-loader:
        condition: service_completed_successfully
    restart: on-failure:3 

    
  meta-loader:
    container_name: meta-loader
    build: ./containers/metamorphical/
    environment:
      - DATABASE_URL=mongodb://database:27017/
      - SCRUB_DB=1
    volumes:
      - ./containers/metamorphical:/metamorphical
    depends_on:
      loader:
        condition: service_completed_successfully


  loader:
    container_name: loader
    build: ./containers/dataset/
    environment:
      - DATABASE_URL=mongodb://database:27017/
      - SCRUB_DB=1
    volumes:
      - ./containers/dataset:/loader
    depends_on:
      - database
    restart: on-failure:5


  database:
    ports:
      - 27017:27017
    image: "mongodb/mongodb-community-server"
